/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pegawai.JadwalFoto;

import Pegawai.DashboardPegawai;
import Pegawai.Pegawai.KelolaPegawai;

import Utill.DBConnection;
import Utill.MessageDialog;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nirleka
 */
public class KelolaJadwalFoto extends javax.swing.JFrame {

    /**
     * Creates new form KelolaJadwalFoto
     */
    public KelolaJadwalFoto() {
        initComponents();
        tampilkanDataKeTabel();
        test();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pelanggan", "Pegawai", "Paket", "Lokasi", "Jadwal Foto", "Tanggal Booking"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);

        jMenu1.setText("Dashboard");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Diri");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        new DashboardPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        new KelolaPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    
    private void test()
    {
        String query = "SELECT * FROM pelanggan";
        ResultSet result = DBConnection.getData(query);
        
//        while (result.next())
//            {
//                model.addRow(new Object[] {
//                    result.getString("ID_Pegawai"),
//                    result.getString("Nama"),
//                    result.getString("Gender"),
//                    result.getString("Alamat"),
//                    result.getString("Telepon"),
//                    result.getString("Jabatan"),
//                    result.getString("Tanggal_Gabung")
//                });
//            }
    }
    
    private void tampilkanDataKeTabel(){
    
         try
        {
            String query = "SELECT " +
                           "jf.ID_Jadwal, " +
                           "p.Nama AS NamaPelanggan, " +
                           "f.Nama AS NamaFotografer, " +
                           "pk.Nama AS NamaPaket, " +
                           "jf.Lokasi, " +
                           "jf.Tanggal_Waktu, " +
                           "jf.Tanggal_Booking " +
                           "FROM jadwal_foto jf " +
                           "LEFT JOIN pelanggan p ON jf.ID_Pelanggan = p.ID_Pelanggan " +
                           "LEFT JOIN pegawai f ON jf.ID_Fotografer = f.ID_Pegawai " +
                           "LEFT JOIN paket pk ON jf.ID_Paket = pk.ID_Paket";


;
            ResultSet result = DBConnection.getData(query);
            
//            String namaPelanggan = "", namaPaket = "", namaFotografer = ""; 

            DefaultTableModel model = (DefaultTableModel) tabel.getModel();
            model.setRowCount(0);

            while (result.next())
            {
                System.out.println("tes");
//                ResultSet cariPelanggan = DBConnection.getData("SELECT * FROM pelanggan WHERE ID_Pelanggan=" + result.getString("ID_Pelanggan"));
//                ResultSet cariFotografer = DBConnection.getData("SELECT * FROM pegawai WHERE ID_Pegawai=" + result.getString("ID_Fotografer"));
//                ResultSet cariPaket = DBConnection.getData("SELECT * FROM paket WHERE ID_Paket=" + result.getString("ID_Paket"));
//                
//                if (cariPelanggan.next() &&
//                    cariFotografer.next() &&
//                    cariPaket.next())
//                {
//                    namaPelanggan = cariPelanggan.getString("Nama");
//                    namaFotografer = cariFotografer.getString("Nama");
//                    namaPaket = cariPaket.getString("Nama");
//                   
//                }else
//                {
//                    System.out.println("Lho hee" + result.getString("ID_Pelanggan"));
//                }
                
                
                model.addRow(new Object[] {
                    result.getString("ID_Jadwal"),
                    result.getString("NamaPelanggan"),
                    result.getString("NamaFotografer"),
                    result.getString("NamaPaket"),
                    result.getString("Lokasi"),
                    result.getString("Tanggal_Waktu"),
                    result.getString("Tanggal_Booking")
                });
            }
        } catch (SQLException e)
        {
            MessageDialog.showProgramErrorMessage(e.getMessage());
        }
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaJadwalFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaJadwalFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaJadwalFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaJadwalFoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaJadwalFoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
