/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pelanggan.HalamanInformasiPemesanan;

import Pelanggann.Pelanggan;


import Utill.DBConnection;
import Utill.MessageDialog;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shidd
 */
public class HalamanInformasiPemesanan extends javax.swing.JFrame {

    /**
     * Creates new form HalamanInformasiPemesanan
     */
    public HalamanInformasiPemesanan() {
        initComponents();
        tampilkanDataKeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jButton1.setText("Kembali Ke Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Pelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tampilkanDataKeTable(){
    
         try
        {
            String query = "SELECT " +
                           "jf.ID_Jadwal, " +
                           "p.Nama AS NamaPelanggan, " +
                           "f.Nama AS NamaFotografer, " +
                           "pk.Nama AS NamaPaket, " +
                           "jf.Lokasi, " +
                           "jf.Tanggal_Waktu, " +
                           "jf.Tanggal_Booking " +
                           "FROM jadwal_foto jf " +
                           "LEFT JOIN pelanggan p ON jf.ID_Pelanggan = p.ID_Pelanggan " +
                           "LEFT JOIN pegawai f ON jf.ID_Fotografer = f.ID_Pegawai " +
                           "LEFT JOIN paket pk ON jf.ID_Paket = pk.ID_Paket";



            ResultSet result = DBConnection.getData(query);
            //            String namaPelanggan = "", namaPaket = "", namaFotografer = ""; 

            DefaultTableModel model = (DefaultTableModel) tabel.getModel();
            model.setRowCount(0);

            while (result.next())
            while (result.next())
            {
                System.out.println("tes");
//                ResultSet cariPelanggan = DBConnection.getData("SELECT * FROM pelanggan WHERE ID_Pelanggan=" + result.getString("ID_Pelanggan"));
//                ResultSet cariFotografer = DBConnection.getData("SELECT * FROM pegawai WHERE ID_Pegawai=" + result.getString("ID_Fotografer"));
//                ResultSet cariPaket = DBConnection.getData("SELECT * FROM paket WHERE ID_Paket=" + result.getString("ID_Paket"));
//                
//                if (cariPelanggan.next() &&
//                    cariFotografer.next() &&
//                    cariPaket.next())
//                {
//                    namaPelanggan = cariPelanggan.getString("Nama");
//                    namaFotografer = cariFotografer.getString("Nama");
//                    namaPaket = cariPaket.getString("Nama");
//                   
//                }else
//                {
//                    System.out.println("Lho hee" + result.getString("ID_Pelanggan"));
//                }
                
                
                model.addRow(new Object[] {
                    result.getString("ID_Jadwal"),
                    result.getString("NamaPelanggan"),
                    result.getString("NamaFotografer"),
                    result.getString("NamaPaket"),
                    result.getString("Lokasi"),
                    result.getString("Tanggal_Waktu"),
                    result.getString("Tanggal_Booking")
                });
            }
        } catch (SQLException e)
        {
            MessageDialog.showProgramErrorMessage(e.getMessage());
        }
    
    
    
    
    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanInformasiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanInformasiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanInformasiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanInformasiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanInformasiPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
