/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Admin.Invoice.KelolaInvoice;
import Admin.Pegawai.KelolaPegawai;
import Admin.JadwalFoto.KelolaJadwalFoto;
import Admin.Paket.KelolaPaket;
import Admin.Pelanggan.KelolaPelanggan;
import Admin.Users.KelolaUsers;

/**
 *
 * @author nirleka
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        tabInvoice = new javax.swing.JMenu();
        tabPegawai = new javax.swing.JMenu();
        tabJadwalFoto = new javax.swing.JMenu();
        tabPaket = new javax.swing.JMenu();
        tabPelanggan = new javax.swing.JMenu();
        tabUsers = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));

        welcomeText.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        welcomeText.setText("Selamat Datang Admin ....");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(welcomeText)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(welcomeText)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        tabInvoice.setText("Invoice");
        tabInvoice.setMargin(new java.awt.Insets(3, 12, 3, 12));
        tabInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabInvoiceMousePressed(evt);
            }
        });
        jMenuBar2.add(tabInvoice);

        tabPegawai.setText("Pegawai");
        tabPegawai.setMargin(new java.awt.Insets(3, 12, 3, 12));
        tabPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabPegawaiMousePressed(evt);
            }
        });
        jMenuBar2.add(tabPegawai);

        tabJadwalFoto.setText("Jadwal foto");
        tabJadwalFoto.setMargin(new java.awt.Insets(3, 12, 3, 12));
        tabJadwalFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabJadwalFotoMousePressed(evt);
            }
        });
        jMenuBar2.add(tabJadwalFoto);

        tabPaket.setText("Paket");
        tabPaket.setMargin(new java.awt.Insets(3, 12, 3, 12));
        tabPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabPaketMousePressed(evt);
            }
        });
        jMenuBar2.add(tabPaket);

        tabPelanggan.setText("Pelanggan");
        tabPelanggan.setMargin(new java.awt.Insets(3, 12, 3, 12));
        tabPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabPelangganMousePressed(evt);
            }
        });
        jMenuBar2.add(tabPelanggan);

        tabUsers.setText("Users");
        tabUsers.setMargin(new java.awt.Insets(3, 12, 3, 12));
        tabUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabUsersMousePressed(evt);
            }
        });
        jMenuBar2.add(tabUsers);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPegawaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPegawaiMousePressed
        new KelolaPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tabPegawaiMousePressed

    private void tabInvoiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabInvoiceMousePressed
        new KelolaInvoice().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tabInvoiceMousePressed

    private void tabJadwalFotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabJadwalFotoMousePressed
        new KelolaJadwalFoto().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tabJadwalFotoMousePressed

    private void tabPaketMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPaketMousePressed
        new KelolaPaket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tabPaketMousePressed

    private void tabPelangganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPelangganMousePressed
        new KelolaPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tabPelangganMousePressed

    private void tabUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabUsersMousePressed
        new KelolaUsers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tabUsersMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu tabInvoice;
    private javax.swing.JMenu tabJadwalFoto;
    private javax.swing.JMenu tabPaket;
    private javax.swing.JMenu tabPegawai;
    private javax.swing.JMenu tabPelanggan;
    private javax.swing.JMenu tabUsers;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
